stages:
  - test

pytest:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml